In [159]:
import pandas as pd

In [160]:
df = pd.read_csv('./datasets/lr_dataset.csv')

In [161]:
df.sample(5)

,prompt,general,smart_home,todo,mail,learning_resources
0,Find a good book on deep learning.,0,0,0,0,1
96,Send me a tutorial for setting up a voice-cont...,0,1,0,0,1
113,"Find me a resource on voice assistants, remind...",1,1,0,1,1
61,Forward the GAN tutorial and also mail me the ...,0,0,0,1,1
32,Can you summarize what 'attention' means in ne...,1,0,0,0,1

In [162]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   prompt              147 non-null    object
 1   general             147 non-null    int64
 2   smart_home          147 non-null    int64
 3   todo                147 non-null    int64
 4   mail                147 non-null    int64
 5   learning_resources  147 non-null    int64
dtypes: int64(5), object(1)
memory usage: 7.0+ KB

In [163]:
# Get the sum of numerical columns
general_sum = df['general'].sum()
smart_home_sum = df['smart_home'].sum()
todo_sum = df['todo'].sum()
mail_sum = df['mail'].sum()
learning_resources_sum = df['learning_resources'].sum()

print(f"General: {general_sum}")
print(f"Smart Home: {smart_home_sum}")
print(f"Todo: {todo_sum}")
print(f"Mail: {mail_sum}")
print(f"Learning Resources: {learning_resources_sum}")

General: 65
Smart Home: 39
Todo: 67
Mail: 54
Learning Resources: 142

In [164]:
# Drop 50 random rows from the datafram where the sum of the columns is not equal to 1
# df = df.drop(df[df[['general', 'smart_home', 'todo', 'mail', 'learning_resources']].sum(axis=1) != 1].sample(30).index)

In [165]:
# Shuffle the data
df = df.sample(frac=1).reset_index(drop=True)

In [166]:
df2 = pd.read_csv('./datasets/bemo_prompts_dataset_v1.csv')

In [167]:
df2.sample(5)

,prompt,general,smart_home,todo,mail
130,Switch on the garden lights and add a reminder...,0,1,1,0
96,What is the history of Rome and add a reminder...,1,0,1,0
48,Schedule a conference call for Monday.,0,0,1,0
241,"Can you tell me a fun fact, lock the front doo...",1,1,1,1
55,Reply to John's email.,0,0,0,1

In [168]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   prompt      250 non-null    object
 1   general     250 non-null    int64
 2   smart_home  250 non-null    int64
 3   todo        250 non-null    int64
 4   mail        250 non-null    int64
dtypes: int64(4), object(1)
memory usage: 9.9+ KB

In [169]:
# Get the sum of numerical columns
general_sum = df2['general'].sum()
smart_home_sum = df2['smart_home'].sum()
todo_sum = df2['todo'].sum()
mail_sum = df2['mail'].sum()

print(f"General: {general_sum}")
print(f"Smart Home: {smart_home_sum}")
print(f"Todo: {todo_sum}")
print(f"Mail: {mail_sum}")

General: 131
Smart Home: 131
Todo: 131
Mail: 131

In [170]:
# Add a new column to the DataFrame 2
df2['learning_resources'] = 0

In [171]:
df2.sample(5)

,prompt,general,smart_home,todo,mail,learning_resources
161,Add 'finish the project' to my tasks and draft...,0,0,1,1,0
25,Start the vacuum cleaner.,0,1,0,0,0
17,Turn on the living room lights.,0,1,0,0,0
73,What is the capital of France and close the wi...,1,1,0,0,0
116,Can you explain quantum physics and forward th...,1,0,0,1,0

In [172]:
# Combine the two DataFrames
df_combined = pd.concat([df, df2], ignore_index=True)

In [173]:
# Shuffle the combined DataFrame
df_combined = df_combined.sample(frac=1).reset_index(drop=True)

In [174]:
df_combined.sample(5)

,prompt,general,smart_home,todo,mail,learning_resources
288,"What is the capital of France, close the windo...",1,1,1,0,0
381,"Open the garage door, set a task to renew my p...",0,1,1,1,0
97,"Show me how to use APIs for smart home apps, m...",0,1,1,1,1
260,How do I cook a perfect meal and adjust the ai...,1,1,0,0,0
227,Set a reminder to exercise at 6 PM and send an...,0,0,1,1,0

In [175]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   prompt              397 non-null    object
 1   general             397 non-null    int64
 2   smart_home          397 non-null    int64
 3   todo                397 non-null    int64
 4   mail                397 non-null    int64
 5   learning_resources  397 non-null    int64
dtypes: int64(5), object(1)
memory usage: 18.7+ KB

In [176]:
# Get the sum of numerical columns
general_sum = df_combined['general'].sum()
smart_home_sum = df_combined['smart_home'].sum()
todo_sum = df_combined['todo'].sum()
mail_sum = df_combined['mail'].sum()
learning_resources_sum = df_combined['learning_resources'].sum()

print(f"General: {general_sum}")
print(f"Smart Home: {smart_home_sum}")
print(f"Todo: {todo_sum}")
print(f"Mail: {mail_sum}")
print(f"Learning Resources: {learning_resources_sum}")

General: 196
Smart Home: 170
Todo: 198
Mail: 185
Learning Resources: 142

In [177]:
# Get the number of rows in the DataFrame where the sum of the numerical columns is 1
num_rows_general = df_combined[
    (df_combined['general'] == 1) &
    (df_combined['smart_home'] == 0) &
    (df_combined['todo'] == 0) &
    (df_combined['mail'] == 0) &
    (df_combined['learning_resources'] == 0)
].shape[0]

num_rows_smart_home = df_combined[
    (df_combined['general'] == 0) &
    (df_combined['smart_home'] == 1) &
    (df_combined['todo'] == 0) &
    (df_combined['mail'] == 0) &
    (df_combined['learning_resources'] == 0)
].shape[0]

num_rows_todo = df_combined[
    (df_combined['general'] == 0) &
    (df_combined['smart_home'] == 0) &
    (df_combined['todo'] == 1) &
    (df_combined['mail'] == 0) &
    (df_combined['learning_resources'] == 0)
].shape[0]

num_rows_mail = df_combined[
    (df_combined['general'] == 0) &
    (df_combined['smart_home'] == 0) &
    (df_combined['todo'] == 0) &
    (df_combined['mail'] == 1) &
    (df_combined['learning_resources'] == 0)
].shape[0]

num_rows_learning_resources = df_combined[
    (df_combined['general'] == 0) &
    (df_combined['smart_home'] == 0) &
    (df_combined['todo'] == 0) &
    (df_combined['mail'] == 0) &
    (df_combined['learning_resources'] == 1)
].shape[0]

print(f"Number of rows with general = 1: {num_rows_general}")
print(f"Number of rows with smart_home = 1: {num_rows_smart_home}")
print(f"Number of rows with todo = 1: {num_rows_todo}")
print(f"Number of rows with mail = 1: {num_rows_mail}")
print(f"Number of rows with learning_resources = 1: {num_rows_learning_resources}")

Number of rows with general = 1: 17
Number of rows with smart_home = 1: 17
Number of rows with todo = 1: 17
Number of rows with mail = 1: 17
Number of rows with learning_resources = 1: 17

In [178]:
# Get the minimum sum of the numerical columns and make them equal
min_sum = min(general_sum, smart_home_sum, todo_sum, mail_sum, learning_resources_sum)
print(f"Minimum sum: {min_sum}")

Minimum sum: 142

In [179]:
# Drop 97 random from the data frame where the sum of the columns is not equal to 1 and where learning resources is not equal to 1
df_combined = df_combined.drop(df_combined[
    (df_combined[['general', 'smart_home', 'todo', 'mail', 'learning_resources']].sum(axis=1) != 1) &
    (df_combined['learning_resources'] != 1)
].sample(80).index)

In [180]:
df_combined.sample(5)

,prompt,general,smart_home,todo,mail,learning_resources
390,Where can I find video lectures on statistics?,0,0,0,0,1
264,How do object detection models work? Give me a...,1,0,0,0,1
165,What's the best movie tonight and email the su...,1,0,0,1,0
367,Add a reminder to pay the electricity bill and...,0,0,1,1,0
317,Can you explain what reinforcement learning is...,1,0,0,0,1

In [181]:
# Get the sum of numerical columns
general_sum = df_combined['general'].sum()
smart_home_sum = df_combined['smart_home'].sum()
todo_sum = df_combined['todo'].sum()
mail_sum = df_combined['mail'].sum()
learning_resources_sum = df_combined['learning_resources'].sum()

print(f"General: {general_sum}")
print(f"Smart Home: {smart_home_sum}")
print(f"Todo: {todo_sum}")
print(f"Mail: {mail_sum}")
print(f"Learning Resources: {learning_resources_sum}")

General: 144
Smart Home: 119
Todo: 149
Mail: 131
Learning Resources: 142

In [184]:
# Get the number of rows in the DataFrame where the sum of the numerical columns is 1
num_rows_general = df_combined[
    (df_combined['general'] == 1) &
    (df_combined['smart_home'] == 0) &
    (df_combined['todo'] == 0) &
    (df_combined['mail'] == 0) &
    (df_combined['learning_resources'] == 0)
].shape[0]

num_rows_smart_home = df_combined[
    (df_combined['general'] == 0) &
    (df_combined['smart_home'] == 1) &
    (df_combined['todo'] == 0) &
    (df_combined['mail'] == 0) &
    (df_combined['learning_resources'] == 0)
].shape[0]

num_rows_todo = df_combined[
    (df_combined['general'] == 0) &
    (df_combined['smart_home'] == 0) &
    (df_combined['todo'] == 1) &
    (df_combined['mail'] == 0) &
    (df_combined['learning_resources'] == 0)
].shape[0]

num_rows_mail = df_combined[
    (df_combined['general'] == 0) &
    (df_combined['smart_home'] == 0) &
    (df_combined['todo'] == 0) &
    (df_combined['mail'] == 1) &
    (df_combined['learning_resources'] == 0)
].shape[0]

num_rows_learning_resources = df_combined[
    (df_combined['general'] == 0) &
    (df_combined['smart_home'] == 0) &
    (df_combined['todo'] == 0) &
    (df_combined['mail'] == 0) &
    (df_combined['learning_resources'] == 1)
].shape[0]

print(f"Number of rows with general = 1: {num_rows_general}")
print(f"Number of rows with smart_home = 1: {num_rows_smart_home}")
print(f"Number of rows with todo = 1: {num_rows_todo}")
print(f"Number of rows with mail = 1: {num_rows_mail}")
print(f"Number of rows with learning_resources = 1: {num_rows_learning_resources}")

Number of rows with general = 1: 17
Number of rows with smart_home = 1: 17
Number of rows with todo = 1: 17
Number of rows with mail = 1: 17
Number of rows with learning_resources = 1: 17

In [185]:
# Save the DataFrame to a CSV file
df_combined.to_csv('./datasets/bemo_prompts_dataset_v1.1.csv', index=False)