In [149]:
import pandas as pd

In [150]:
df = pd.read_csv('./datasets/bemo_prompts_dataset_v1.2.csv')

In [151]:
df.sample(5)

,prompt,general,smart_home,todo,mail,others
114,Activate the security alarm.,0,1,0,0,0
284,Start the vacuum cleaner and draft an email re...,0,1,0,1,0
12,Send an update email about the project.,0,0,0,1,0
168,What are the benefits of meditation and send a...,1,0,0,1,0
208,Add 'buy groceries' to my list and compose an ...,0,0,1,1,0

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   prompt      300 non-null    object
 1   general     300 non-null    int64
 2   smart_home  300 non-null    int64
 3   todo        300 non-null    int64
 4   mail        300 non-null    int64
 5   others      300 non-null    int64
dtypes: int64(5), object(1)
memory usage: 14.2+ KB

In [153]:
# Drop the rows where others are not equal to 1
df = df[df['others'] == 1]

In [154]:
df.sample(5)

                            prompt  general  smart_home  todo  mail  others
203               How do you work?        0           0     0     0       1
76              What is your name?        0           0     0     0       1
31   Do you learn from experience?        0           0     0     0       1
77         Can you solve problems?        0           0     0     0       1
253        Can you provide advice?        0           0     0     0       1

In [155]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51 entries, 17 to 298
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   prompt      51 non-null     object
 1   general     51 non-null     int64
 2   smart_home  51 non-null     int64
 3   todo        51 non-null     int64
 4   mail        51 non-null     int64
 5   others      51 non-null     int64
dtypes: int64(5), object(1)
memory usage: 2.8+ KB

In [156]:
# Get the sum of numerical columns
general_sum = df['general'].sum()
smart_home_sum = df['smart_home'].sum()
todo_sum = df['todo'].sum()
mail_sum = df['mail'].sum()
others_sum = df['others'].sum()

print(f"General: {general_sum}")
print(f"Smart Home: {smart_home_sum}")
print(f"Todo: {todo_sum}")
print(f"Mail: {mail_sum}")
print(f"Others: {others_sum}")

General: 1
Smart Home: 0
Todo: 0
Mail: 0
Others: 51

In [157]:
# Show me the row where the general is 1
general_df = df[df['general'] == 1]

In [158]:
# Remove the rows where the general is 1
df = df[df['general'] != 1]

In [159]:
# Get the sum of numerical columns
general_sum = df['general'].sum()
smart_home_sum = df['smart_home'].sum()
todo_sum = df['todo'].sum()
mail_sum = df['mail'].sum()
others_sum = df['others'].sum()

print(f"General: {general_sum}")
print(f"Smart Home: {smart_home_sum}")
print(f"Todo: {todo_sum}")
print(f"Mail: {mail_sum}")
print(f"Others: {others_sum}")

General: 0
Smart Home: 0
Todo: 0
Mail: 0
Others: 50

In [160]:
# Add learning_resources column
df['learning_resources'] = 0

In [161]:
df.sample(5)

,prompt,general,smart_home,todo,mail,others,learning_resources
206,What is your favorite food?,0,0,0,0,1,0
277,Do you get tired?,0,0,0,0,1,0
141,Are you self-aware?,0,0,0,0,1,0
211,How do you spend your time?,0,0,0,0,1,0
124,What is your opinion on art?,0,0,0,0,1,0

In [162]:
df2 = pd.read_csv('./datasets/bemo_prompts_dataset_v1.1.csv')

In [163]:
df2.sample(5)

,prompt,general,smart_home,todo,mail,learning_resources
222,Activate the home surveillance system.,0,1,0,0,0
76,Email me a breakdown of supervised learning wi...,0,0,0,1,1
128,"Start the vacuum cleaner, add 'finish the proj...",0,1,1,1,0
176,Turn on the living room lights and send an ema...,0,1,0,1,0
198,Mail a set of lessons for learning APIs and sh...,0,0,0,1,1

In [164]:
# Add others column to df2
df2['others'] = 0

In [165]:
# Combine the two dataframes
df_combined = pd.concat([df, df2], ignore_index=True)

In [166]:
# Get the sum of numerical columns
general_sum = df_combined['general'].sum()
smart_home_sum = df_combined['smart_home'].sum()
todo_sum = df_combined['todo'].sum()
mail_sum = df_combined['mail'].sum()
others_sum = df_combined['others'].sum()
learning_resources_sum = df_combined['learning_resources'].sum()

print(f"General: {general_sum}")
print(f"Smart Home: {smart_home_sum}")
print(f"Todo: {todo_sum}")
print(f"Mail: {mail_sum}")
print(f"Learning Resources: {learning_resources_sum}")
print(f"Others: {others_sum}")

General: 144
Smart Home: 119
Todo: 149
Mail: 131
Learning Resources: 142
Others: 50

In [167]:
# Reorder the columns making the others column the last one
df_combined = df_combined[['prompt', 'general', 'smart_home', 'todo', 'mail', 'learning_resources', 'others']]

In [168]:
df_combined.sample(5)

,prompt,general,smart_home,todo,mail,learning_resources,others
6,What is your origin?,0,0,0,0,0,1
354,"Help me understand autonomous systems, add it ...",1,0,1,1,1,0
337,Set a reminder to exercise at 6 PM.,0,0,1,0,0,0
0,Are you available 24/7?,0,0,0,0,0,1
298,Email the summary of the meeting.,0,0,0,1,0,0

In [169]:
# Save the dataframe to a csv file
df_combined.to_csv('./datasets/bemo_prompts_dataset_v1.3.csv', index=False)